---
title: "moreindocovid.Rmd"
output: html_document
---

```{r}
library("plotly")
library("lubridate")
library("tidyr")
library("dplyr")
```

```{r}
table1 <- read.csv("daily-tests-and-daily-new-confirmed-covid-cases.csv")
```
```{r}
table1 <- table1[table1$Entity == "Singapore" | table1$Entity == "Malaysia" | table1$Entity == "Indonesia" ,c(1,3,6)]
```

```{r}
table1 <- reshape(table1, idvar="Day", timevar="Entity", direction="wide")
table1
```

```{r}
colnames(table1) <- c("Date","Indonesia","Malaysia","Singapore")
table1$Date <- ymd(table1$Date)
cases <- table1
```

```{r}
# cases$ConfirmedCases.Indonesia <- round(cases$ConfirmedCases.Indonesia,2)
# cases$ConfirmedCases.Malaysia <- round(cases$ConfirmedCases.Malaysia,2)
# cases$ConfirmedCases.Singapore <- round(cases$ConfirmedCases.Singapore,2)

cases$Indonesia <- as.integer(cases$Indonesia)
cases$Malaysia <- as.integer(cases$Malaysia)
cases$Singapore <- as.integer(cases$Singapore)

```
```{r}
cases <- cases[order(cases$Date),]
```
```{r}
fig <- plot_ly(cases, x = ~Date, y = ~Indonesia, name = 'Indonesia', type='scatter',mode = 'lines')
fig <- fig %>% add_trace(y = ~Singapore, name = 'Singapore', mode = 'lines')
fig <- fig %>% add_trace(y = ~Malaysia, name = 'Malaysia', mode = 'lines')
y <- list(
  title="Positive Cases On A 7 Day Average (linear)"
)
title <- (
  title="Positive COVID Cases"
)
fig <- fig %>% layout(yaxis=y, title=title)
fig
```

```{r}
htmlwidgets::saveWidget(as_widget(fig), "secondchart.html")

```

```{r}
table2 <- read.csv("daily-tests-and-daily-new-confirmed-covid-cases.csv", stringsAsFactors = FALSE)
```

```{r}
tests <- table2[table2$Entity == 'Indonesia' | table2$Entity == 'Singapore' | table2$Entity == 'Malaysia', c(3, 1, 4) ]
```

```{r}
#tests <- tests[,-2]
tests
```
```{r}
tests$Day <- ymd(tests$Day)
```

```{r}
tests <- data.frame(tests$Day, tests$Entity, tests$new_tests_7day_smoothed)
```
```{r}
colnames(tests) <- c("date","country", "new_tests_7days")
```
```{r}
tests <- reshape(tests, idvar="date", timevar="country", direction="wide")
```
```{r}
colnames(tests) <- c("Date", "Indonesia", "Malaysia", "Singapore")
```

```{r}
# tests <- tests[,-2]
```
```{r}
nrow(tests)
```

```{r}
nrow(cases)
```

```{r}
rate <- left_join(tests, cases, by="Date")
```

```{r}
colnames(rate) <- c("Date","Indonesia_Tests","Malaysia_Tests", "Singapore_Test", "Indonesia_Cases", "Malaysia_Cases", "Singapore_Cases")
```

```{r}
positive_rate <- data.frame(rate$Date, round(rate$Indonesia_Cases/rate$Indonesia_Tests,2)*100,round(rate$Singapore_Cases/rate$Indonesia_Tests,2)*100,round(rate$Malaysia_Cases/rate$Malaysia_Tests,2)*100)
```

```{r}
colnames(positive_rate) <- c("Date", "Indonesia", "Singapore", "Malaysia")
# positive_rate$Indonesia <- as.integer(positive_rate$Indonesia)
# positive_rate$Singapore <- as.integer(positive_rate$Singapore)
# positive_rate$Malaysia <- as.integer(positive_rate$Malaysia)

```
```{r}
positive_rate <- positive_rate[order(positive_rate$Date),]
```
```{r}
fig3 <- plot_ly(positive_rate, x = ~Date, y = ~Indonesia, name = 'Indonesia', type='scatter', mode = 'lines')
fig3 <- fig3 %>% add_trace(y = ~Singapore, name = 'Singapore', mode = 'lines')
fig3 <- fig3 %>% add_trace(y = ~Malaysia, name = 'Malaysia', mode = 'lines')
y <- list(
  title="Positive Rate On A 7 Day Average (linear)"
)
title <- (
  title="Positive Rate COVID Cases (# tests that came out positive)"
)
fig3 <- fig3 %>% layout(yaxis=y, title=title)
fig3
```

```{r}
htmlwidgets::saveWidget(as_widget(fig3), "third_chart.html")

```